config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  resources :documents do
    member do
      post 'download'
    end
  end
  resources :document_data
  resources :news_categories

  # root_path
  root :to => 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :document_datum, dependent: :destroy
end

app/models/document_datum.rb
class DocumentDatum < ApplicationRecord
  belongs_to :document
end

app/models/news_category.rb
class NewsCategory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/documents_controller.rb
require 'open-uri'

class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :download, :edit, :update, :destroy]
  before_action :set_document_data, only: [:show]

  def index
    @documents = Document.all
  end

  def show
  end

  def download
    doc = open(@document.url)
    if doc.content_type == "application/pdf"
      filename = Time.current.strftime("%Y%m%d%H%M%S") + "_" + @document.name.to_s + ".pdf"
      download_file = Rails.root.join("public", "download_files", filename)
      open(download_file, "w+b") do |out|
        out.write(doc.read)
      end

      @document_datum = @document.document_datum.create(file_name: filename, document_type: "pdf")
    end

    respond_to do |format|
      format.html { redirect_to @document, notice: 'Document was successfully downloaded.' }
      format.json { head :no_content }
    end
  end

  def new
    @document = Document.new
  end

  def edit
  end

  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def set_document_data
      @document_data = @document.document_datum.all
    end

    def document_params
      params.require(:document).permit(:name, :url)
    end
end

app/controllers/news_categories_controller.rb
class NewsCategoriesController < ApplicationController
  before_action :set_news_category, only: [:show, :edit, :update, :destroy]

  def index
    @news_categories = NewsCategory.all
  end

  def show
  end

  def new
    @news_category = NewsCategory.new
  end

  def edit
  end

  def create
    @news_category = NewsCategory.new(news_category_params)

    respond_to do |format|
      if @news_category.save
        format.html { redirect_to @news_category, notice: 'News category was successfully created.' }
        format.json { render :show, status: :created, location: @news_category }
      else
        format.html { render :new }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @news_category.update(news_category_params)
        format.html { redirect_to @news_category, notice: 'News category was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_category }
      else
        format.html { render :edit }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @news_category.destroy
    respond_to do |format|
      format.html { redirect_to news_categories_url, notice: 'News category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_news_category
      @news_category = NewsCategory.find(params[:id])
    end

    def news_category_params
      params.require(:news_category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def download_file_path(file_name)
    if File.exist?(Rails.root.join("public", "download_files", file_name))
      "/download_files/#{file_name}"
    end
  end
end

app/helpers/news_categories_helper.rb
module NewsCategoriesHelper
end

app/views/dashboard/index.html.haml
%p#notice= notice
%h1 Dashboard

app/views/documents/_form.html.haml
= form_with(model: document, local: true) do |form|
  - if document.errors.any?
    #error_explanation
      %h2
        = pluralize(document.errors.count, "error")
        prohibited this document from being saved:
      %ul
        - document.errors.full_messages.each do |message|
          %li= message
  .field.mb-3
    = form.label :name
    = form.text_field :name, class: "form-control", placeholder: "document name"
  .field.mb-3
    = form.label :url
    = form.text_field :url, class: "form-control", placeholder: "https://example.pdf"
  .actions.text-center.mb-3
    = form.submit class: "btn btn-primary btn-lg"

app/views/documents/edit.html.haml
.col-md-6.mx-auto
  %h2.py-2.text-center
    Editing Document
  = render 'form', document: @document
  %hr
  .text-right
    = link_to 'Show', @document, role: "button", class: "btn btn-outline-info"
    = link_to 'Back to Index', documents_path, role: "button", class: "btn btn-link"

app/views/documents/index.html.haml
.mx-auto
  - if notice
    .alert.alert-primary.alert-dismissible.fade.show{role: "alert"}
      = notice
      %button.btn.btn-secondary{type: "button", class: "close small", data: {dismiss: "alert"}, aria: {label: "close"} }
        %span{aria: { hidden: "true"} } ✕
  %h2.py-2.text-center
    Index Documents
  %table.table.table-striped.table-hover.table-sm
    %thead.thead-dark
      %tr
        %th Name
        %th Url
        %th{:colspan => "3"}
    %tbody
      - @documents.each do |document|
        %tr{:class => "document_#{document.id}"}
          %td= document.name
          %td
            = link_to document.url, document.url, :target => "_blank"
          %td= link_to 'Show', document, role: "button", class: "btn btn-outline-info btn-sm"
          %td= link_to 'Edit', edit_document_path(document), role: "button", class: "btn btn-outline-secondary btn-sm"
          %td= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class: "btn btn-outline-danger btn-sm"
  %hr
  .actions.text-center.mb-3
    = link_to 'New Document', new_document_path, class: "btn btn-primary btn-lg"

app/views/documents/new.html.haml
.col-md-6.mx-auto
  %h1.py-2.text-center
    New Document
  = render 'form', document: @document
  %hr
  .text-right
    = link_to 'Back to Index', documents_path, role: "button", class: "btn btn-link"

app/views/documents/show.html.haml
.mx-auto
  - if notice
    .alert.alert-primary.alert-dismissible.fade.show{role: "alert"}
      = notice
      %button.btn.btn-secondary{type: "button", class: "close small", data: {dismiss: "alert"}, aria: {label: "close"} }
        %span{aria: { hidden: "true"} } ✕
  %h2.py-2.text-center
    Show Document
  %hr 
  .field.mb-3
    %dt Name:
    %dd
      = @document.name
  .field.mb-3
    %dt Url:
    %dd
      = @document.url
  .text-right
    = link_to 'Get Document', download_document_path(@document), method: :post, role: "button", class: "btn btn-outline-info"
    = link_to 'Edit', edit_document_path(@document), role: "button", class: "btn btn-outline-secondary"
    = link_to 'Back to Index', documents_path, role: "button", class: "btn btn-link"
  %hr
  %table.table.table-striped.table-hover.table-sm
    %thead.thead-dark
      %tr
        %th file_aame
        %th md5
        %th note
        %th created_at
        %th
    %tbody
      - @document_data.each do |document_datum|
        %tr{:class => "document_data_#{document_datum.id}"}
          %td= document_datum.file_name
          %td= document_datum.md5sum
          %td= document_datum.note
          %td= document_datum.created_at
          %td
            - if download_file_path(document_datum.file_name).present?
              = link_to "Download", download_file_path(document_datum.file_name), role: "button", class: "btn btn-outline-info btn-sm"
            - #if download_file_path(document_datum.file_name).present?
              = #link_to "Edit", edit_document_datum_path(document_datum), role: "button", class: "btn btn-outline-secondary btn-sm"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AppName
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
      = link_to "Home", "/", class: "navbar-brand"
      %button.navbar-toggler.navbar-toggler-right{:type => "button", :data => {:toggle => 'collapse', :target => '#navbarNav'}, :aria => {:controls => 'navbarNav', :expanded => 'false', :label => 'Toggle navigation'}}
        %span.navbar-toggler-icon
      %div.napse.navbar-collapse#navbarNav
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            = link_to "Documents", documents_path, class: "nav-link"
          %li.nav-item
            = link_to "News Categories", news_categories_path, class: "nav-link"
          %li.nav-item
            = link_to "Settings", root_path, class: "nav-link disabled"
    %main
      .jumbotron
        #content_view
          = yield

app/views/news_categories/_form.html.haml
= form_with(model: news_category, local: true) do |form|
  - if news_category.errors.any?
    #error_explanation
      %h2
        = pluralize(news_category.errors.count, "error")
        prohibited this news_category from being saved:
      %ul
        - news_category.errors.full_messages.each do |message|
          %li= message
  .field.mb-3
    = form.label :name
    = form.text_field :name, class: "form-control", placeholder: "document name"
  .actions.text-center.mb-3
    = form.submit class: "btn btn-primary btn-lg"

app/views/news_categories/edit.html.haml
.col-md-6.mx-auto
  %h2.py-2.text-center
    Editing NewsCategory
  = render 'form', news_category: @news_category
  %hr
  .text-right
    = link_to 'Show', @news_category, role: "button", class: "btn btn-outline-info"
    = link_to 'Back to Index', news_categories_path, role: "button", class: "btn btn-link"

app/views/news_categories/index.html.haml
.mx-auto
  - if notice
    .alert.alert-primary.alert-dismissible.fade.show{role: "alert"}
      = notice
      %button.btn.btn-secondary{type: "button", class: "close small", data: {dismiss: "alert"}, aria: {label: "close"} }
        %span{aria: { hidden: "true"} } ✕
  %h2.py-2.text-center
    Index NewsCategories
  %table.table.table-striped.table-hover.table-sm
    %thead.thead-dark
      %tr
        %th Name
        %th{:colspan => "3"}
    %tbody
      - @news_categories.each do |news_category|
        %tr{:class => "document_#{news_category.id}"}
          %td= news_category.name
          %td= link_to 'Show', news_category, role: "button", class: "btn btn-outline-info btn-sm"
          %td= link_to 'Edit', edit_news_category_path(news_category), role: "button", class: "btn btn-outline-secondary btn-sm"
          %td= link_to 'Destroy', news_category, method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class: "btn btn-outline-danger btn-sm"
  %hr
  .actions.text-center.mb-3
    = link_to 'New NewsCategory', new_news_category_path, class: "btn btn-primary btn-lg"

app/views/news_categories/new.html.haml
.col-md-6.mx-auto
  %h2.py-2.text-center
    New NewsCategory
  = render 'form', news_category: @news_category
  %hr
  .text-right
    = link_to 'Back to Index', news_categories_path, role: "button", class: "btn btn-link"

app/views/news_categories/show.html.haml
.col-md-6.mx-auto
  - if notice
    .alert.alert-primary.alert-dismissible.fade.show{role: "alert"}
      = notice
      %button.btn.btn-secondary{type: "button", class: "close small", data: {dismiss: "alert"}, aria: {label: "close"} }
        %span{aria: { hidden: "true"} } ✕
  %h2.py-2.text-center
    Show Document
  %hr
  .field.mb-3
    %dt Name:
    %dd
      = @news_category.name
  .text-right
    = link_to 'Edit', edit_news_category_path(@news_category), role: "button", class: "btn btn-outline-secondary"
    = link_to 'Back to Index', news_categories_path, role: "button", class: "btn btn-link"